### ISSUE TITLE
project relationship to terraform-provider-fastly

### ISSUE THREAD

**Issue by chenrui333** [fastly/waflyctl#108]
👋  My understanding is with Fastly WAF v2, we can completely use terarform-provider-fastly to do the WAF configuration changes, so my question is we no longer need this tool to manage WAF configs right?

I am asking is because I saw some internal docs referencing this tool and want to double check in here. Thanks!!

**Comment by squeemishly** [comment]
Hi @chenrui333 excellent question. The problem here is that many of our customers would rather have our Solutions team generate their WAFs for them. In that case, we don't want to use Terraform to create their WAF, instead, we need a quick way to configure everything that's needed for each service. That's really where this tool is going to be continued to be used. To stand up an NG WAF, Solutions passes in the `--ng-api` flag.

**Comment by chenrui333** [comment]
I see. Does that also mean, if we have terraform code for WAF, we can totally replace it with terraform provider for IaC the configurations? Thanks!

**Comment by squeemishly** [comment]
I'm sorry, I don't quite understand. What's IaC? But, if you are managing a WAF with terraform, you definitely don't need this project. In fact, they would have a conflict because waflyctl wouldn't tell terraform to update the state.

**Comment by chenrui333** [comment]
>  In fact, they would have a conflict because waflyctl wouldn't tell terraform to update the state.

this is what I want, thank you!

IaC is infra-as-code, sorry about the acronym.

I think I have got what I need, thanks @squeemishly!
